version: '3.4'

services:

  api:
    image: nikolara5/vega-api:2.0
    ports:  
      - "8088:7000"
    restart: on-failure
    depends_on:
      - database
    environment:
      DB_PATH: host=database;port=5432;database=VegaDB;username=postgres;password=postgres
      DB_PROVIDER: Postgres

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "VegaDB"
    ports:
      - 5454:5432
